Hameg HM813x/Hameg HM813x.ini

Only basic functionality: Amplitude and frequency

New driver for the Hameg function generator HM8131 and HM8133

---

Rigol DSG3000/Rigol DSG3000.ini
Rigol DSG3000/Rigol DSG3000.py

New driver for the Rigol DSG300

---

Stanford_SRS844/Stanford_SRS844.ini
Stanford_SRS844/Stanford_SRS844.py

This is basically a fork of the SRS830 driver 1.1, adapted for the SRS844, which simply means that channels have been removed if they do
not apply to the SRS844.

Driver for Stanford SRS844

---

Triton/Triton.ini
Triton/Triton.py
Triton/readme.md

Added a ton of features, mainly support for magnets and temperature control.

Triton feature boost

---

UserInput/UserInput.ini
UserInput/UserInput.py
UserInput/readme.md

A virtual driver to ask the user for input.

User Input driver

---

Stanford_SRS830/Stanford_SRS830.py

In our labs we saw rare malformed responses from different SRS830. This commit catches these.

SRS830: Fixes for malformed device response

---

Oxford IPS120/Oxford IPS120.ini
Oxford IPS120/Oxford IPS120.py

New driver for the Oxford IPS120. Note, that this driver is for the IPS not the PS version.

Oxford IPS120: New driver

---

Cryomagnetics LM510/Cryomagnetics LM510.ini
Cryomagnetics LM510/Cryomagnetics LM510.py

New driver for this level meter.

New driver: Cryomagnetics LM510 levelmeter

---

Keysight_MXA_SA_MODE/Keysight_MXA_SA_MODE-UpgradeCfg.py
Keysight_MXA_SA_MODE/Keysight_MXA_SA_MODE.py
Keysight_MXA_SA_MODE/Keysight_SA.ini

New driver for Keysight Signal Analyzer

New Driver for Keysight

---

Signal Recovery 726x/Signal Recovery 726x.ini
Signal Recovery 726x/Signal Recovery 726x.py

This is for the Signal Recovery 7265 and 7260 lock-in amplifiers. (Also branded as Ametek and EG&G with same model numbers)

Signal recovery 726x

---

PXI_Aeroflex302x/PXI_Aeroflex302x.py
PXI_Aeroflex302x/PXI_Aeroflex302x_SignalGenerator.ini
PXI_Aeroflex302x/afSigGenWrapper.py
PXI_Aeroflex303x/PXI_Aeroflex303x.py
PXI_Aeroflex303x/PXI_Aeroflex303x_Digitizer.ini
PXI_Aeroflex303x/afDigitizerWrapper.py

Updated the drivers for the Aeroflex PXI units to the lastest version used at Chalmers.

Aeroflex units

---

MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.ini
MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.py
MultiQubit_PulseGenerator/sequence.py
MultiQubit_PulseGenerator/sequence_rb.py

Identity gate is required to implement full clifford groups.
And please ignore MultiQubit_PulseGenerator/sequence_rb.py. (it is still in process)

Add Identity gate

---

MultiQubit_PulseGenerator/sequence_builtin.py

Correcting timing between pulses for C-phase Echo sequence

Corrections to C-phase gate

---

MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.ini
MultiQubit_PulseGenerator/crosstalk.py
MultiQubit_PulseGenerator/predistortion.py
MultiQubit_PulseGenerator/sequence.py

Adds support for predistortion and flux crosstalk in multi-qubit driver. These modules have been tested.

Predistortion and Crosstalk drivers

---

MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.ini
MultiQubit_PulseGenerator/readout.py
MultiQubit_PulseGenerator/sequence.py

add readout IQ offset and skew; also, clean up trailing whitespace (thanks SublimeText)

add readout IQ offset, skew

---

Keysight_33622A_WaveformGenerator/Keysight_33622A_WaveformGenerator.ini
Keysight_33622A_WaveformGenerator/Keysight_33622A_WaveformGenerator.py

Driver for Keysight benchtop awg

---

MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.ini
MultiQubit_PulseGenerator/readout.py

Added the option to have uniform (default) or individual readout amplitudes.

Added non-uniform readout amplitudes

---

MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.ini
MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.py
MultiQubit_PulseGenerator/readout.py

To be able to distinguish between positive and negative frequencies. Doubles the available readout bandwidth.

Added the option to do demodulation of a complex input signal

---

Acqiris_U1084A/Acqiris_U1084A_Digitizer.ini
MultiQubit_PulseGenerator/sequence.py
MultiQubit_PulseGenerator/sequence_builtin.py

Due to some merge issues, there's some "noise" in the commit history here. The meaningful changes are f6ecf6d, 81ccf7c, f1c270c, and e348f6b.

fix pulse spacing in Pulse Sequencer; change Aquiris U1084 default mode

---

MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.ini
MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.py
MultiQubit_PulseGenerator/readout.py

note that number of records will be removed in future version, should
be handled by size of trace

added single-shot readout

---

MultiQubit_PulseGenerator/sequence_rb.py

- Keep the format of psi and unitary gates consistent with other drivers.
ground state = [0, 1]
excited state = [1, 0]
- See http://www.vcpc.univie.ac.at/~ian/hotlist/qc/talks/bloch-sphere-rotations.pdf  for details.

multi-qubit rb

---

MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.ini
MultiQubit_PulseGenerator/sequence.py
MultiQubit_PulseGenerator/tomography.py

Developed driver to allow for 2 qubit state tomography fluently in labber.

2 qubit state tomography

---

Keysight_PXI_AWG/Keysight_PXI_AWG.py
Keysight_PXI_Digitizer/Keysight_PXI_Digitizer.py

Reports the current trace while hardware looping. Also clears the AWG memory before uploading new traces.

Fixes to pxi systems

---

MultiQubit_PulseGenerator/sequence.py

After discussion with @mortenkjaergaard

Fixes bug with timing of overlapping pulses

---

MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.ini
MultiQubit_PulseGenerator/MultiQubit_PulseGenerator.py
MultiQubit_PulseGenerator/gates.py
MultiQubit_PulseGenerator/sequence_builtin.py

Makes spin-locking sequence available to the sequence selection menu. Three different spin-locking sequences are possible, SL-3, SL-5a and SL-5b (for additional information, see https://www.nature.com/articles/ncomms3337).

Added spin-locking experiment to Multi-qubit driver.
